name: test
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: node:18.20
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_DB: rcr_api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up JDK 11 for Liquibase
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jdk
          architecture: x64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Run migrations
        env:
          DATABASE_HOST: "postgres"
          DATABASE_USERNAME: "postgres"
          DATABASE_PASSWORD: "example"
          DATABASE_PORT: "5432"
        run: npm run liquibase:migrate

      - name: Run test
        env:
          DATABASE_HOST: "postgres"
          DATABASE_USERNAME: "postgres"
          DATABASE_PASSWORD: "example"
          DATABASE_PORT: "5432"
        run: npm run test
